using Blackbird.Applications.Sdk.Common.Exceptions;
using HtmlAgilityPack;

namespace Apps.Sanity.Utils;

public static class HtmlHelper
{
    public static string ExtractContentId(string html)
    {
        var doc = new HtmlDocument();
        doc.LoadHtml(html);

        var metaNode = doc.DocumentNode.SelectSingleNode("//meta[@name='blackbird-content-id']");
        if (metaNode != null)
        {
            var contentAttr = metaNode.GetAttributeValue("content", null);
            return contentAttr;
        }

        throw new PluginMisconfigurationException(
            "Unable to locate the content ID in the provided HTML file. Ensure the file is correctly generated by the Sanity Blackbird app and is not corrupted.");
    }
}