using Apps.Sanity.Models;
using Blackbird.Applications.Sdk.Common.Exceptions;
using HtmlAgilityPack;

namespace Apps.Sanity.Utils;

public static class HtmlHelper
{
    public static string ExtractContentId(string html)
    {
        var doc = new HtmlDocument();
        doc.LoadHtml(html);

        var metaNode = doc.DocumentNode.SelectSingleNode("//meta[@name='blackbird-content-id']");
        if (metaNode != null)
        {
            var contentId = metaNode.GetAttributeValue("content", null!);
            if (!string.IsNullOrEmpty(contentId))
            {
                return contentId;
            }
        }

        var mainContentDiv = doc.DocumentNode.SelectSingleNode("//div[@data-content-id]");
        if (mainContentDiv != null)
        {
            var contentId = mainContentDiv.GetAttributeValue("data-content-id", null!);
            if (!string.IsNullOrEmpty(contentId))
            {
                return contentId;
            }
        }

        throw new PluginMisconfigurationException(
            "Unable to locate the content ID in the provided HTML file. Ensure the file is correctly generated by the Sanity Blackbird app and is not corrupted.");
    }

    public static LocalizationStrategy ExtractLocalizationStrategy(string html)
    {
        var doc = new HtmlDocument();
        doc.LoadHtml(html);

        var metaNode = doc.DocumentNode.SelectSingleNode("//meta[@name='blackbird-localization-strategy']");
        if (metaNode != null)
        {
            var strategyValue = metaNode.GetAttributeValue("content", null!);
            if (!string.IsNullOrEmpty(strategyValue) && Enum.TryParse<LocalizationStrategy>(strategyValue, out var strategy))
            {
                return strategy;
            }
        }

        return LocalizationStrategy.FieldLevel;
    }

    public static List<string> ExtractReferencedContentIds(HtmlDocument doc)
    {
        var result = new HashSet<string>();
        var referencesSection = doc.DocumentNode.SelectSingleNode("//div[@id='referenced-entries']");
        if (referencesSection != null)
        {
            var refDivs = referencesSection.SelectNodes(".//div[@data-content-id]");
            if (refDivs != null)
            {
                foreach (var div in refDivs)
                {
                    var contentId = div.GetAttributeValue("data-content-id", null!);
                    if (!string.IsNullOrEmpty(contentId) && !contentId.StartsWith("image-"))
                    {
                        result.Add(contentId);
                    }
                }
            }
        }

        return result.ToList();
    }
}